version: "3"

services:

  hacker-rank-problems:
    build: .
    ports:
      - 5005:5005
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/Library/Caches/Coursier:/root/.cache/coursier" # MacOS Coursier cache
#      - "~/.cache/coursier:/root/.cache/coursier" # Linux Coursier cache
#      - "~/AppData/Local/Coursier/Cache:/root/.cache/coursier" # Windows Coursier cache
      - ".:/opt/hacker-rank-problems"
      - "/opt/hacker-rank-problems/target"
      - "/opt/hacker-rank-problems/project/target"
      - "/root/.sbt/1.0/plugins"
